-- Reclamos del Libro de Reclamaciones (migracion desde Netlify Forms).
--
-- El formulario publico NO escribe aqui directamente: envia a la funcion
-- serverless /api/reclamo, que valida, sube los adjuntos y hace el INSERT con
-- la SERVICE ROLE KEY. Por eso, a proposito, NO existe politica de INSERT para
-- "anon": nadie puede escribir esta tabla desde el navegador (mas cerrado que
-- la tabla "leads"). El panel admin (pestana Reclamos) lee y actualiza estado.
--
-- COMO APLICAR:
--   1) Supabase -> SQL Editor -> New query -> pegar TODO este archivo -> Run.
--   2) Storage -> New bucket -> nombre "reclamos", Public = OFF (privado,
--      igual que "vouchers"). Las politicas de abajo dejan listo el acceso.

create table public.reclamos (
  id uuid primary key default gen_random_uuid(),
  numero bigint generated by default as identity,   -- correlativo: codigo LR-2026-0001
  created_at timestamptz not null default now(),
  tipo text not null,                               -- Retraso / Equipaje / ...
  nombre text not null,
  dni text,
  telefono text not null,
  email text,
  detalle text not null,
  respuesta_preferida text,                         -- Telefono / Correo / Presencial
  sucursal text,
  adjuntos jsonb not null default '[]'::jsonb,      -- [{path, nombre, tipo, size}]
  estado text not null default 'pendiente'
    check (estado in ('pendiente', 'en_atencion', 'respondido')),
  respondido_at timestamptz,                        -- para acreditar el plazo legal
  ip text,
  user_agent text
);

alter table public.reclamos enable row level security;

-- Solo el admin puede LEER y ACTUALIZAR (la service key de la funcion salta
-- RLS, por eso no necesita politica propia).
create policy "reclamos_select_admin" on public.reclamos
  for select using (public.is_admin());

create policy "reclamos_update_admin" on public.reclamos
  for update using (public.is_admin()) with check (public.is_admin());

grant select, update on public.reclamos to authenticated;
grant all on public.reclamos to service_role;

-- Ordenar los mas recientes primero en el panel.
create index reclamos_created_at_idx on public.reclamos (created_at desc);

-- Adjuntos: bucket PRIVADO "reclamos" (crearlo a mano, paso 2 de arriba).
-- La funcion sube con la service key; el admin abre los archivos con URLs
-- firmadas, que requieren poder hacer SELECT sobre el objeto:
create policy "reclamos_files_admin_read" on storage.objects
  for select using (bucket_id = 'reclamos' and public.is_admin());
