-- Migracion de los datos del Google Sheet a la tabla promotions.
-- Extraido automaticamente del Sheet original -- revisar en el panel
-- admin (pestaña Promociones) despues de correr esto, por si falta
-- alguna fila o alguna URL quedo mal transcrita.

insert into public.promotions (category, image_url, title, display_order) values
('carouselpromos', 'https://i.postimg.cc/fygYthsP/Angeles-Vegas-Canon-USA.jpg', 'Promo-USA', 1),
('carouselpromos', 'https://i.postimg.cc/3JdXMWCQ/Carnavales-Peruanos.jpg', 'Promo-Peru', 2),
('carouselpromos', 'https://i.postimg.cc/JzXjng2N/Gran-Tour-Europa.jpg', 'Promo-Europa', 3),
('carouselpromos', 'https://i.postimg.cc/HLCX7zGb/Turquia-y-Dubai.jpg', 'Promo-Dubai', 4),
('carouselpromos', 'https://i.postimg.cc/bJr8Tt7z/Donde-El-Sol.jpg', 'Promo-CentroAmerica', 5),
('carouselpromos', 'https://i.postimg.cc/hjvgrdkf/Febrero-promos.jpg', 'Promo-Febrero', 6),
('carouselpromos', 'https://i.postimg.cc/HLs46YBM/Coreo-Pekin-Shangai.jpg', 'Promo-Asia', 7),
('carouselpromos', 'https://i.postimg.cc/q7MX1Jjy/India-triangulo-dorado-7d.jpg', 'Promo-Asia', 8),

('carouselnorteamerica', 'https://i.postimg.cc/vm3bfzSS/Angeles-Vegas-Canon-USA.jpg', 'NA-Angeles-Vegas-Canon-USA', 1),
('carouselnorteamerica', 'https://i.postimg.cc/VNDmnRV6/Costa-Mujeres.jpg', 'NA-Costa-Mujeres', 2),
('carouselnorteamerica', 'https://i.postimg.cc/FRzmZLMv/Costa-Mujeres-2.jpg', 'NA-Costa-Mujeres', 3),
('carouselnorteamerica', 'https://i.postimg.cc/nzrZkDyG/Mundial-2026.jpg', 'NA-World-Cup', 4),
('carouselnorteamerica', 'https://i.postimg.cc/d13vByb9/New-York-Washingtong-USA.jpg', 'NA-New-York', 5),
('carouselnorteamerica', 'https://i.postimg.cc/fLPsgbsc/Rivera-Maya.jpg', 'NA-Rivera-Maya', 6),
('carouselnorteamerica', 'https://i.postimg.cc/d1fFS0Fm/Rivera-Maya-2.jpg', 'NA-Rivera-Maya', 7),
('carouselnorteamerica', 'https://i.postimg.cc/76R4QL4V/Vegas-Canon-USA.jpg', 'NA-Vegas-Canon', 8),
('carouselnorteamerica', 'https://i.postimg.cc/cHzW5JWT/Washingtong-NY-Boston-USA.jpg', 'NA-Washingtong', 9),
('carouselnorteamerica', 'https://i.postimg.cc/bwmWHHnG/NA-Orlando.jpg', 'NA-Orlando', 10),
('carouselnorteamerica', 'https://i.postimg.cc/MT319HDh/NA-Circuitos-Turisticos-USA.jpg', 'NA-Circuito-USA', 11),

('carouselcentroamerica', 'https://i.postimg.cc/mrt1ctmm/CA-Curacao.jpg', 'CA-Curacao', 1),
('carouselcentroamerica', 'https://i.postimg.cc/7LfJCfKV/CA-Isla-Feliz.jpg', 'CA-Isla-Feliz', 2),
('carouselcentroamerica', 'https://i.postimg.cc/zfVHLVxp/CA-Montego-Bay.jpg', 'CA-Montego-Bay', 3),
('carouselcentroamerica', 'https://i.postimg.cc/zfVHLVxk/CA-Punta-Cana.jpg', 'CA-Punta-Cana', 4),
('carouselcentroamerica', 'https://i.postimg.cc/ZqCv9CwH/CA-Varadero.jpg', 'CA-Varadero', 5),
('carouselcentroamerica', 'https://i.postimg.cc/qRq0L3P2/Jamaica-2.jpg', 'CA-Jamaica-2', 6),
('carouselcentroamerica', 'https://i.postimg.cc/4d0GF3G9/Punta-Cana.jpg', 'CA-Punta-Cana', 7),
('carouselcentroamerica', 'https://i.postimg.cc/W3yVf4VZ/Punta-Cana-2.jpg', 'CA-Punta-Cana', 8),
('carouselcentroamerica', 'https://i.postimg.cc/V6hwHNwX/Punta-Cana-3.jpg', 'CA-Punta-Cana', 9),
('carouselcentroamerica', 'https://i.postimg.cc/V6hwHNwg/Vive-Varadero.jpg', 'CA-Varadero', 10),

('carouselsudamerica', 'https://i.postimg.cc/rsz612tg/Carnavales-Peruanos.jpg', 'SA-Peru', 1),
('carouselsudamerica', 'https://i.postimg.cc/1zJswHYj/Atacama-Chile.jpg', 'SA-Chile', 2),
('carouselsudamerica', 'https://i.postimg.cc/KYJxBNsq/Cartagena.jpg', 'SA-Colombia', 3),
('carouselsudamerica', 'https://i.postimg.cc/tg2pW5M7/Colombia.jpg', 'SA-Colombia', 4),
('carouselsudamerica', 'https://i.postimg.cc/1tXPHqk3/Escapada-Medellin.jpg', 'SA-Colombia', 5),
('carouselsudamerica', 'https://i.postimg.cc/qRq0L3Pn/Iguazu.jpg', 'SA-Argentina', 6),
('carouselsudamerica', 'https://i.postimg.cc/XJq38CRw/Medellin.jpg', 'SA-Colombia', 7),
('carouselsudamerica', 'https://i.postimg.cc/63qw0vk0/Patagonia-Chile.jpg', 'SA-Chile', 8),
('carouselsudamerica', 'https://i.postimg.cc/cHCZmnph/Puerto-Varas-Chile.jpg', 'SA-Chile', 9),
('carouselsudamerica', 'https://i.postimg.cc/mDn46r4Q/Rio-de-Janeiro.jpg', 'SA-Brazil', 10),
('carouselsudamerica', 'https://i.postimg.cc/G2fRSpRP/Rio-y-Buzios.jpg', 'SA-Brazil', 11),

('carouselasia', 'https://i.postimg.cc/q7j4yL5v/China-Milenaria.jpg', 'Asia-China-Milenaria', 1),
('carouselasia', 'https://i.postimg.cc/NMFY4H3G/Dubai.jpg', 'Asia-Dubai', 2),
('carouselasia', 'https://i.postimg.cc/xCZQFdQP/Turquia-y-Dubai.jpg', 'Asia-Turquia-Dubai', 3),
('carouselasia', 'https://i.postimg.cc/ZqKFwbVd/China-Tokio.jpg', 'Asia-China-Tokio', 4),
('carouselasia', 'https://i.postimg.cc/zfXSxz0W/Corea-Japon.jpg', 'Asia-Corea-Japon', 5),
('carouselasia', 'https://i.postimg.cc/HLs46YBM/Coreo-Pekin-Shangai.jpg', 'Asia-Corea-Pekin-Shangai', 6),
('carouselasia', 'https://i.postimg.cc/q7MX1Jjy/India-triangulo-dorado-7d.jpg', 'Asia-India-7d', 7),
('carouselasia', 'https://i.postimg.cc/TPYqtdC9/India-triangulo-dorado-con-varanasi.jpg', 'Asia-India-Varanasi', 8),
('carouselasia', 'https://i.postimg.cc/TP7jSz4g/India-Yoga-Meditacion-10d9n.jpg', 'Asia-India-10d', 9),
('carouselasia', 'https://i.postimg.cc/q7MX1Jjj/Mejor-India-Nepal-12d.jpg', 'Asia-India-12d', 10),

('carouseleuropa', 'https://i.postimg.cc/q7j4yL5q/Conoce-Europa.jpg', 'EU-Europa-Tour', 1),
('carouseleuropa', 'https://i.postimg.cc/k4G9cb0D/Gran-Tour-Europa.jpg', 'EU-Europa-Tour', 2),
('carouseleuropa', 'https://i.postimg.cc/V6v1RCxv/Grecia.jpg', 'EU-Grecia', 3),
('carouseleuropa', 'https://i.postimg.cc/FRzmZLMd/Grecia-2.jpg', 'EU-Grecia', 4),
('carouseleuropa', 'https://i.postimg.cc/d13vBybZ/Grecia-3.jpg', 'EU-Grecia', 5),
('carouseleuropa', 'https://i.postimg.cc/zBv5jgsw/Mega-Europa-Especial-II.jpg', 'EU-Europa-Tour', 6),
('carouseleuropa', 'https://i.postimg.cc/ydGKrNKy/Tour-Europa.jpg', 'EU-Europa-Tour', 7),
('carouseleuropa', 'https://i.postimg.cc/Jn5bZKyf/EU-Londres-Madrid.jpg', 'EU-Europa-Tour', 8);
