// Londres y París (Iti OC321 sábados / OC320 martes) — catálogo Europa Occidental 26/27, pág. 24.
module.exports = {
  slug: 'londres-y-paris',
  title: 'Londres y París',
  dias: '7 días',
  desde: '1,205',
  subtitle: 'Londres y París cruzando el Canal de la Mancha por el Eurotunnel: dos capitales en una sola escapada.',
  metaDescription: 'Circuito Londres y París desde Perú: dos capitales europeas en 7 días desde $1,205, cruzando el Canal de la Mancha por el Eurotunnel. Cotiza en cuotas con Viajes LM-REPS.',
  eyebrow: 'Paquete · Europa / Reino Unido y Francia',
  region: 'carouseleuropa',
  destino: 'Reino Unido y Francia',
  countries: ['reino-unido', 'francia'],
  hero: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Westminster_palace.jpg/1280px-Westminster_palace.jpg',
  card: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Eiffelturm.JPG/1280px-Eiffelturm.JPG',
  salidasChip: 'Salidas los sábados o martes a Londres',
  ruta: ['Londres', 'París'],
  subtituloHighlights: 'Del Big Ben a la Torre Eiffel, cruzando el Canal de la Mancha',
  highlights: [
    '<strong>Londres:</strong> sus principales avenidas y monumentos, con el cambio de guardia en Buckingham',
    '<strong>Eurotunnel:</strong> cruce del Canal de la Mancha en tren (en algunas salidas, en ferry)',
    '<strong>París:</strong> recorrido de la ciudad terminando en la Torre Eiffel, con subida opcional al 2º piso',
    '<strong>Paseo opcional en Bateaux Mouche</strong> por el Sena',
    '<strong>Versalles opcional:</strong> el palacio y sus famosos jardines',
  ],
  galeria: [
    ['https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Westminster_palace.jpg/1280px-Westminster_palace.jpg', 'Palacio de Westminster y Big Ben, Londres'],
    ['https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Buckingham_Palace_from_gardens%2C_London%2C_UK_-_Diliff_%28cropped%29.jpg/1280px-Buckingham_Palace_from_gardens%2C_London%2C_UK_-_Diliff_%28cropped%29.jpg', 'Palacio de Buckingham, Londres'],
    ['https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Tower_of_London_%28Foto_Hilarmont%29.jpg/1280px-Tower_of_London_%28Foto_Hilarmont%29.jpg', 'Torre de Londres'],
    ['https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Eiffelturm.JPG/1280px-Eiffelturm.JPG', 'Torre Eiffel, París'],
  ],
  itinerario: [
    { titulo: 'América → Vuelo a Londres', texto: 'Salida en vuelo intercontinental con destino a Londres.' },
    {
      titulo: 'Londres — Llegada',
      img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Westminster_palace.jpg/1280px-Westminster_palace.jpg',
      texto: 'Llegada al aeropuerto de Heathrow y traslado al hotel. Tiempo libre para tomar contacto con la ciudad y pasear por el centro comercial de esta gran urbe; este día no hay presencia de guía acompañante. Alojamiento.',
    },
    {
      titulo: 'Londres — Visita de ciudad',
      img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Buckingham_Palace_from_gardens%2C_London%2C_UK_-_Diliff_%28cropped%29.jpg/1280px-Buckingham_Palace_from_gardens%2C_London%2C_UK_-_Diliff_%28cropped%29.jpg',
      texto: 'Desayuno en el hotel y salida para hacer la visita de la ciudad, recorriendo sus principales avenidas y monumentos, y terminando frente al <strong>Palacio de Buckingham</strong> para asistir al cambio de guardia si se realiza ese día. Tarde libre. Sugerimos un paseo opcional por los famosos "Docks", visitando alguno de sus históricos "Pubs". Alojamiento.',
    },
    { titulo: 'Londres → París por el Eurotunnel', texto: 'Desayuno y salida hacia Folkestone, donde nuestro bus abordará el tren que nos conducirá a través del Canal de la Mancha por el <strong>Eurotunnel</strong> (en algunas salidas, en ferry). Llegada a Calais y continuación por carretera a París, donde llegaremos a media tarde. Alojamiento.' },
    {
      titulo: 'París — Torre Eiffel',
      img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Eiffelturm.JPG/1280px-Eiffelturm.JPG',
      texto: 'Desayuno buffet. Salida para efectuar el recorrido de la ciudad, sus principales avenidas y monumentos, terminando en la <strong>Torre Eiffel</strong>, con la oportunidad de subir a ella para admirar una bella panorámica de todo París. <em class="small">(Subida a la torre Eiffel 2º piso: Paquete Plus P+.)</em> Tarde libre; oportunidad de hacer un paseo opcional en el famoso Bateaux Mouche por el Sena <em class="small">(Paseo: Paquete Plus P+)</em> y quizás acercarnos a Montmartre y el Barrio Latino. Alojamiento.',
    },
    { titulo: 'París — Día libre (Versalles opcional)', texto: 'Desayuno buffet en el hotel. Destinaremos este día a pasear libremente por la ciudad, sus paseos y bulevares. Sugerimos una visita opcional a <strong>Versalles</strong> para conocer su bello palacio y famosos jardines. Alojamiento. <em class="small">(Las visitas en París se realizarán cualquier día durante la estancia, según disponibilidad de entradas y reservas.)</em>' },
    { titulo: 'París → Vuelo de regreso', texto: 'Desayuno. A la hora prevista, traslado al aeropuerto para tomar el vuelo de salida.' },
  ],
  incluye: [
    'Traslados aeropuerto ↔ hotel a la llegada y salida',
    'Alojamiento + desayuno buffet en hoteles de categoría elegida',
    'Transporte en bus y tren en Eurotunnel de Londres a París (en algunas salidas, en ferry)',
    'Visitas indicadas en el itinerario con guías locales de habla hispana',
    'Audífonos individuales',
    'Seguro de protección y asistencia en viaje MAPAPLUS',
  ],
  noIncluye: [
    'Vuelos internacionales',
    'Impuesto de ciudad: <strong>$36 USD</strong>, al reservar',
    'Comidas no indicadas',
    'Gastos personales',
  ],
  plus: {
    precio: '65',
    comidas: [],
    extras: ['Paseo en Bateaux Mouche', 'Subida a la torre Eiffel (2º piso)'],
  },
  precios: {
    columnas: ['May – Jun', 'Jul – Ago', 'Sep – Oct', 'Nov – Feb 27*', 'Dic (fechas especiales)', 'Mar – Abr 27'],
    mejorCol: 3,
    filas: [
      { tour: '7 días<br><small class="text-muted fw-normal">Londres / París (sábados)<br>Iti OC321</small>', categoria: 'Confort 3*/4*', valores: ['1,375', '1,265', '1,375', '1,205', '1,265', '1,310'] },
      { tour: '', categoria: 'Superior 4*', valores: ['1,530', '1,395', '1,530', '1,355', '1,395', '1,455'] },
      { tour: '7 días<br><small class="text-muted fw-normal">Londres / París (martes)<br>Iti OC320</small>', categoria: 'Confort 3*/4*', valores: ['1,345', '1,260', '1,345', '1,190', '1,260', '1,305'] },
      { tour: '', categoria: 'Superior 4*', valores: ['1,480', '1,440', '1,480', '1,355', '1,440', '1,450'] },
    ],
    nota: '*Salida sábado: nov-feb 27 excepto 19-26 dic; suplemento individual $535 (resto temporada) / $445 · Salida martes: nov-feb 27 excepto 22-29 dic; suplemento individual $535/$400 · Impuesto de ciudad $36 se paga al reservar',
  },
  hoteles: [
    { ciudad: 'Londres', confort: 'Holiday Inn Express Royal Docks', superior: 'The Gantry' },
    { ciudad: 'París', confort: 'B&B Porte d\'Orléans / Ibis Porte d\'Orléans / Ibis La Défense', superior: 'Mercure Porte d\'Orléans / Novotel La Défense' },
  ],
  fechas: {
    libre: '<strong>A Londres (sábados):</strong> may 02, 09, 16, 23 · jun 06, 13, 20, 27 · jul 04, 11, 18, 25 · ago 01, 08, 15, 22, 29 · sep 05, 12, 19, 26 · oct 03, 10, 17, 24, 31 · nov 07, 14, 21, 28 · dic 05, 12, 19, 26.<br><strong>A Londres (martes):</strong> may 05, 12, 19, 26 · jun 02, 09, 16, 23, 30 · jul 07, 14, 21, 28 · ago 04, 11, 18, 25 · sep 01, 08, 15, 22, 29 · oct 06, 13, 20, 27 · nov 03, 10, 17, 24 · dic 01, 08, 15, 22, 29. <span class="text-muted">Fechas de salida 2026; también hay salidas 2027 (ene–abr).</span>',
  },
  relacionados: [
    { slug: 'paris-y-londres', title: 'París y Londres', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Eiffelturm.JPG/1280px-Eiffelturm.JPG' },
    { slug: 'desde-roma-a-paris-o-londres', title: 'Desde Roma a París o Londres', img: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?q=80&w=800' },
    { slug: 'desde-paris-a-madrid', title: 'Desde París a Madrid', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Eiffelturm.JPG/1280px-Eiffelturm.JPG' },
  ],
  cta: '¿Te animas a conocer Londres y París en una sola escapada?',
};
