// Portugal Eterno (IB138) — catálogo España, Portugal y Marruecos 26/27, pág. 19-20.
module.exports = {
  slug: 'portugal-eterno',
  title: 'Portugal Eterno',
  dias: '9 días',
  desde: '1,460',
  subtitle: 'Lisboa, Óbidos, Batalha, Coímbra, Valle del Duero, Braga, Guimarães, Oporto, Aveiro y Fátima.',
  metaDescription: 'Circuito Portugal Eterno desde Perú: Lisboa, Coímbra, Braga, Oporto y Fátima en 9 días desde $1,460. Cotiza en cuotas con Viajes LM-REPS.',
  eyebrow: 'Paquete · Europa / Portugal',
  region: 'carouseleuropa',
  destino: 'Portugal',
  countries: ['portugal'],
  hero: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Treppenaufgang_Bom_Jesus_do_Monte.jpg/1280px-Treppenaufgang_Bom_Jesus_do_Monte.jpg',
  card: 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?q=80&w=800',
  salidasChip: 'Salidas los lunes',
  ruta: ['Lisboa', 'Óbidos', 'Batalha', 'Coímbra', 'Valle del Duero', 'Braga', 'Guimarães', 'Oporto', 'Aveiro', 'Fátima'],
  subtituloHighlights: 'Portugal de norte a sur, en su esencia más pura',
  highlights: [
    '<strong>Óbidos y Batalha:</strong> la villa amurallada y el monasterio gótico de Santa María de la Victoria (Plus P+)',
    '<strong>Coímbra:</strong> su histórica universidad y el barrio de Santa Cruz',
    '<strong>Valle del Duero y Braga:</strong> viñedos en terrazas y el santuario del Bom Jesus do Monte',
    '<strong>Oporto:</strong> visita de ciudad, paseo en barco y bodegas junto al Duero (Plus P+)',
    '<strong>Fátima y Lisboa:</strong> el santuario mariano y una noche de fados portugueses (Plus P+)',
  ],
  galeria: [
    ['https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Universidad_de_Co%C3%ADmbra%2C_Portugal%2C_2012-05-10%2C_DD_12.JPG/1280px-Universidad_de_Co%C3%ADmbra%2C_Portugal%2C_2012-05-10%2C_DD_12.JPG', 'Universidad de Coímbra'],
    ['https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Treppenaufgang_Bom_Jesus_do_Monte.jpg/1280px-Treppenaufgang_Bom_Jesus_do_Monte.jpg', 'Santuario del Bom Jesus do Monte, Braga'],
    ['https://images.unsplash.com/photo-1555881400-74d7acaacd8b?q=80&w=800', 'Ribeira de Oporto'],
    ['https://upload.wikimedia.org/wikipedia/commons/0/0f/Ria_de_Aveiro_edited_%28cropped%29.jpg', 'Canal de Aveiro con barcos moliceiro'],
    ['https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Sanctuary_of_Fatima.jpg/1280px-Sanctuary_of_Fatima.jpg', 'Santuario de Fátima'],
    ['https://images.unsplash.com/photo-1585208798174-6cedd86e019a?q=80&w=800', 'Tranvía de Lisboa'],
  ],
  itinerario: [
    { titulo: 'América → Vuelo a Portugal', texto: 'Salida en vuelo intercontinental con destino a Lisboa.' },
    { titulo: 'Lisboa — Llegada', texto: 'Llegada y traslado al hotel para tomar el primer contacto con la ciudad. Alojamiento.' },
    {
      titulo: 'Lisboa → Óbidos → Nazaré → Batalha → Coímbra', km: '267 km',
      img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/%C3%93bidos_view592.jpg/1280px-%C3%93bidos_view592.jpg',
      texto: 'Desayuno buffet y salida hacia <strong>Óbidos</strong>, una de las villas más hermosas y mejor preservadas de Portugal. Seguimos camino hasta Nazaré, población pesquera famosa por sus playas y sus formidables olas. Continuamos hasta Batalha, con tiempo libre para almorzar <em class="small">(Almuerzo: Paquete Plus P+.)</em> y visitar el <strong>monasterio de Santa María de la Victoria</strong>. Continuación hasta Coímbra, conocida mundialmente por su universidad. Cena en el hotel.',
    },
    {
      titulo: 'Coímbra → Viseu → Valle del Duero → Braga', km: '197 km',
      img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Alto_Douro_Vinhateiro_visto_de_um_comboio.jpg/1280px-Alto_Douro_Vinhateiro_visto_de_um_comboio.jpg',
      texto: 'Desayuno buffet y visita a Coímbra, donde podremos ver parte del patio de las escuelas y del barrio de Santa Cruz, el corazón de la ciudad. Salimos rumbo a Viseu, hermosa localidad amurallada, y continuamos por el <strong>Valle del Duero</strong>, una región de localidades pintorescas y una de las zonas más famosas en la producción de vino de Portugal. Al finalizar el día llegamos a Braga. Cena en el hotel.',
    },
    {
      titulo: 'Braga → Bom Jesus → Guimarães → Oporto', km: '244 km',
      img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Treppenaufgang_Bom_Jesus_do_Monte.jpg/1280px-Treppenaufgang_Bom_Jesus_do_Monte.jpg',
      texto: 'Desayuno buffet. Visita al <strong>santuario del Bom Jesus do Monte</strong> y salida hacia la pintoresca Guimarães, conocida como "la cuna de la Nación Portuguesa". Tiempo libre para almorzar. <em class="small">(Almuerzo: Paquete Plus P+.)</em> Continuación de viaje hacia Oporto. Alojamiento.',
    },
    {
      titulo: 'Oporto — Visita de ciudad',
      img: 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?q=80&w=1200',
      texto: 'Desayuno buffet. Por la mañana, visita de la ciudad, una de las más bellas y ricas del país, cuyos vinos son famosos en el mundo entero. <em class="small">(Almuerzo: Paquete Plus P+.)</em> Tarde libre. Proponemos un paseo en barco terminando en una de sus famosas bodegas. <em class="small">(Paseo + bodega: Paquete Plus P+.)</em>',
    },
    {
      titulo: 'Oporto → Aveiro → Fátima → Lisboa', km: '341 km',
      img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Sanctuary_of_Fatima.jpg/1280px-Sanctuary_of_Fatima.jpg',
      texto: 'Desayuno buffet y salida hacia <strong>Aveiro</strong>, la "ciudad de los canales", la Venecia portuguesa. Continuación a <strong>Fátima</strong>, uno de los centros de peregrinación de la cristiandad, con tiempo libre para visitar la basílica. <em class="small">(Almuerzo: Paquete Plus P+.)</em> Continuación a Lisboa, donde por la noche escucharemos los bellos "fados" portugueses con una sabrosa cena. <em class="small">(Cena + fados: Paquete Plus P+.)</em>',
    },
    { titulo: 'Lisboa — Torre de Belém y los Jerónimos', texto: 'Desayuno buffet. Por la mañana, visita de la bella Lisboa junto a la desembocadura del río Tajo: sus principales avenidas y monumentos, como la <strong>Torre de Belém</strong> y el <strong>monasterio de los Jerónimos</strong>. Tarde libre; sugerimos una visita a las cercanas Sintra y Cascais, con sus villas y palacios. <em class="small">(Visita: Paquete Plus P+.)</em>' },
    { titulo: 'Lisboa → Vuelo de regreso', texto: 'Desayuno buffet. A la hora prevista, traslado al aeropuerto. Fin del viaje y de nuestros servicios.' },
  ],
  incluye: [
    'Traslados aeropuerto ↔ hotel',
    'Alojamiento + desayuno buffet (categoría elegida)',
    'Visitas panorámicas con guía local: Oporto y Lisboa',
    'Guía acompañante todo el recorrido',
    'Audífonos individuales',
    'Media pensión en Coímbra y Braga (cena incluida)',
    'Bus turístico durante todo el recorrido',
    'Seguro MAPAPLUS',
  ],
  noIncluye: [
    'Vuelos internacionales',
    'Impuesto de ciudad: <strong>$20 USD</strong> (al reservar)',
    'Comidas no indicadas',
    'Gastos personales',
  ],
  plus: {
    precio: '305',
    comidas: ['Almuerzo en Batalha', 'Almuerzo en Guimarães', 'Almuerzo en Oporto', 'Almuerzo en Fátima', 'Cena en Lisboa'],
    extras: ['Paseo en barco en Oporto', 'Visita a bodegas y degustación en Oporto', 'Excursión a Sintra y Cascais', 'Espectáculo de fados portugueses'],
  },
  precios: {
    columnas: ['May – Jun', 'Jul – Ago', 'Sep – Oct'],
    mejorCol: 0,
    filas: [
      { tour: '9 días<br><small class="text-muted fw-normal">Lisboa / Lisboa<br>IB138</small>', categoria: 'Confort 3*/4*', valores: ['1,460', '1,485', '1,460'] },
      { tour: '', categoria: 'Superior 4*', valores: ['1,625', '1,645', '1,625'] },
    ],
    nota: 'Suplemento individual: $605 (Confort) / $770 (Superior) · Impuesto de ciudad $20 USD se paga al reservar',
  },
  hoteles: [
    { ciudad: 'Lisboa', confort: 'Vip Zurique / Acta Moa', superior: 'Vip Grand Lisbon / Vila Galé / Lutecia Smart' },
    { ciudad: 'Coímbra', ambos: 'Coímbra By Affiliated Meliá' },
    { ciudad: 'Braga', ambos: 'Mercure Braga' },
    { ciudad: 'Oporto', confort: 'Star Inn / Holiday Inn Exponor / B&B Porto Gaia', superior: 'AC Porto / Boeira Garden / H Inn Porto Gaia' },
  ],
  fechas: {
    libre: 'Salidas los <strong>lunes</strong> hacia Lisboa, cada semana entre <strong>mayo y octubre de 2026</strong>. Consulta con tu asesor por fechas de 2027.',
  },
  relacionados: [
    { slug: 'esencia-de-portugal-y-madrid', title: 'Esencia de Portugal y Madrid', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Sanctuary_of_Fatima.jpg/1280px-Sanctuary_of_Fatima.jpg' },
    { slug: 'oporto-lisboa-y-madrid', title: 'Oporto, Lisboa y Madrid con Crucero del Duero', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Alto_Douro_Vinhateiro_visto_de_um_comboio.jpg/1280px-Alto_Douro_Vinhateiro_visto_de_um_comboio.jpg' },
    { slug: 'portugal-y-andalucia', title: 'Portugal y Andalucía', img: '/Assets/img/espana/espana-alhambra.jpg' },
  ],
  cta: '¿Te animas al Portugal eterno?',
};
