// Querida Europa (Iti OC270/OC271/OC272) — catálogo Europa Occidental 26/27, pág. 64-65.
// Caja de datos cubre 3 variantes: 18 días Madrid/Roma, 21 días Madrid/Barcelona,
// 22 días Madrid/Madrid. Arranca en Madrid (San Sebastián, Burdeos, Región del
// Loira) hacia París, el Rin, Alemania, Suiza (Lugano) e Italia, cerrando en
// Costa Azul y Barcelona. Categorías Confort 3*/4* y Superior 4*.
module.exports = {
  slug: 'querida-europa',
  title: 'Querida Europa',
  dias: '18, 21 o 22 días',
  desde: '2,960',
  subtitle: 'Madrid, San Sebastián, Burdeos, la región del Loira, París, un paseo en barco por el río Rin, Frankfurt, Heidelberg, Estrasburgo, Basilea, Lucerna, Lugano, Como, Milán, Venecia, Florencia, Siena, Asís, Roma, Costa Azul y Barcelona.',
  metaDescription: 'Circuito Querida Europa: España, Francia, Alemania, Suiza e Italia desde Madrid, 18 a 22 días desde $2,960. Cotiza en cuotas con Viajes LM-REPS.',
  eyebrow: 'Paquete · Europa / España, Francia, Alemania, Suiza e Italia',
  region: 'carouseleuropa',
  destino: 'España, Francia, Alemania, Suiza e Italia',
  countries: ['espana', 'francia', 'alemania', 'suiza', 'italia'],
  hero: 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?q=80&w=1600',
  card: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Bordeaux_place_de_la_bourse_with_tram.JPG/1280px-Bordeaux_place_de_la_bourse_with_tram.JPG',
  salidasChip: 'Salidas los viernes a Madrid',
  ruta: ['Madrid', 'San Sebastián', 'Burdeos', 'Región del Loira', 'París', 'El Rin', 'Frankfurt', 'Heidelberg', 'Estrasburgo', 'Basilea', 'Lucerna', 'Lugano', 'Como', 'Milán', 'Venecia', 'Padua', 'Florencia', 'Siena', 'Asís', 'Roma', 'Pisa', 'Costa Azul', 'Barcelona', 'Zaragoza'],
  subtituloHighlights: 'De Madrid a Roma cruzando media Europa Occidental',
  highlights: [
    '<strong>Madrid, San Sebastián y Burdeos:</strong> el Madrid moderno con Toledo opcional y la "bella Easo" camino a Francia',
    '<strong>Región del Loira y París:</strong> uno de sus famosos castillos y la Torre Eiffel, con Versalles opcional',
    '<strong>El Rin, Heidelberg, Estrasburgo y Basilea:</strong> paseo en barco incluido y la capital de Alsacia camino a Suiza',
    '<strong>Lucerna, Lugano y Como:</strong> paisajes alpinos camino al Duomo de Milán',
    '<strong>Venecia y Florencia:</strong> dos noches en cada una, con góndola y museo de la Academia opcionales',
    '<strong>Siena, Asís y Roma:</strong> la Plaza del Campo, las basílicas de San Francisco y el Vaticano opcional, cerrando en Costa Azul y Barcelona',
  ],
  galeria: [
    ['/Assets/img/espana/espana-madrid.jpg', 'Plaza Mayor, Madrid'],
    ['https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Bordeaux_place_de_la_bourse_with_tram.JPG/1280px-Bordeaux_place_de_la_bourse_with_tram.JPG', 'Place de la Bourse, Burdeos'],
    ['https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Eiffelturm.JPG/1280px-Eiffelturm.JPG', 'Torre Eiffel, París'],
    ['https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Kapellbruecke.JPG/1280px-Kapellbruecke.JPG', 'Puente de la Capilla, Lucerna'],
    ['https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Piazza_San_Marco_%28Venice%29_at_night-msu-2021-6449-.jpg/1280px-Piazza_San_Marco_%28Venice%29_at_night-msu-2021-6449-.jpg', 'Plaza de San Marcos, Venecia'],
    ['https://images.unsplash.com/photo-1552832230-c0197dd311b5', 'Coliseo, Roma'],
  ],
  itinerario: [
    { titulo: 'América → Vuelo a Madrid', texto: 'Salida en vuelo intercontinental con destino a Madrid.' },
    { titulo: 'Madrid — Llegada', texto: 'Llegada y traslado al hotel. Tiempo libre para nuestro primer contacto con la ciudad. Opcionalmente, a última hora de la tarde, recorrido por el <strong>Madrid iluminado</strong> con degustación de tapas en uno de sus múltiples mesones. <em class="small">(Cena de tapas y Madrid iluminado: Paquete Plus P+.)</em> Alojamiento.' },
    { titulo: 'Madrid — Visita de ciudad (Toledo opcional)', texto: 'Desayuno buffet. Visita de la ciudad, sus principales monumentos y el Madrid moderno. <em class="small">(Almuerzo: Paquete Plus P+.)</em> Por la tarde, excursión opcional a la vecina ciudad imperial de <strong>Toledo</strong>, para pasear por sus calles y respirar su ambiente medieval. <em class="small">(Visita a Toledo: Paquete Plus P+.)</em> Alojamiento.' },
    { titulo: 'Madrid → San Sebastián → Burdeos', km: '690 km', texto: 'Desayuno buffet y salida hacia <strong>San Sebastián</strong>, "la bella Easo". Breve panorámica en bus de la ciudad. Continuación hacia Francia. Llegada a Burdeos. Alojamiento.' },
    { titulo: 'Burdeos → Región del Loira → París', km: '610 km', texto: 'Desayuno buffet y salida hacia la región de los castillos del <strong>Loira</strong>, donde haremos una parada para admirar exteriormente uno de sus famosos castillos. Continuación a París. Alojamiento.' },
    {
      titulo: 'París — La Torre Eiffel',
      img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Eiffelturm.JPG/1280px-Eiffelturm.JPG',
      texto: 'Desayuno buffet. Recorrido de la ciudad, sus principales avenidas y monumentos, terminando en la <strong>Torre Eiffel</strong>, con oportunidad de subir a ella. <em class="small">(Subida a la torre Eiffel 2º piso: Paquete Plus P+.)</em> Tarde libre; posibilidad de un paseo opcional en Bateaux Mouche por el Sena y de acercarnos a Montmartre y el Barrio Latino. Alojamiento.',
    },
    { titulo: 'París — Día libre (Versalles opcional)', texto: 'Desayuno buffet en el hotel. Día para pasear libremente por la ciudad, sus paseos y bulevares. Sugerimos una visita opcional a <strong>Versalles</strong>, su bello palacio y famosos jardines. <em class="small">(Las visitas en París se realizarán cualquier día de la estancia, según disponibilidad.)</em> Alojamiento.' },
    { titulo: 'París → Frankfurt "Paseo por el río Rin"', km: '620 km', texto: 'Desayuno buffet y salida hacia la región del Champagne, prosiguiendo el viaje a Alemania hasta las orillas del río Rin, por el que haremos un delicioso <strong>paseo en barco</strong>, embarcando en Boppard hasta St. Goar (incluido). <em class="small">(Almuerzo snack en el barco: Paquete Plus P+.)</em> Continuación a Frankfurt, con tiempo para pasear por su centro. Alojamiento.' },
    { titulo: 'Frankfurt → Heidelberg → Estrasburgo → Basilea', km: '359 km', texto: 'Desayuno. Salida hacia una de las ciudades más hermosas de Alemania, <strong>Heidelberg</strong>, a orillas del río Neckar, con la universidad más antigua del país y un imponente castillo. Continuación a la frontera francesa y llegada a <strong>Estrasburgo</strong>, capital de Alsacia y sede del Parlamento Europeo. Continuación a <strong>Basilea</strong>, con las torres de su esbelta catedral y el pintoresco Ayuntamiento. Alojamiento. <em class="small">(En algunas salidas, alojamiento en Mulhouse, Francia.)</em>' },
    { titulo: 'Basilea → Lucerna → Lugano → Milán', km: '349 km', texto: 'Desayuno. Salida hacia <strong>Lucerna</strong>, bella ciudad a orillas del Lago de los Cuatro Cantones, con sus callejuelas medievales en torno a la Plaza del Ciervo y la Plaza de los Molinos. Continuación a través de Suiza hacia Lugano, en la zona italiana del país, para cruzar la frontera a Como, atravesando una región de hermosos paisajes y lagos. Llegada a Milán. Alojamiento.' },
    { titulo: 'Milán → Lago de Garda → Verona → Venecia', km: '300 km', texto: 'Desayuno buffet. Salida hacia Sirmione, en el Lago de Garda, con tiempo libre para disfrutar de sus paisajes. <em class="small">(Almuerzo en Sirmione: Paquete Plus P+.)</em> Continuación a Verona, la ciudad de Romeo y Julieta, con tiempo libre en su centro histórico. Llegada a última hora de la tarde a Venecia. Alojamiento en alrededores (Mestre).' },
    {
      titulo: 'Venecia — Plaza de San Marcos',
      img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Piazza_San_Marco_%28Venice%29_at_night-msu-2021-6449-.jpg/1280px-Piazza_San_Marco_%28Venice%29_at_night-msu-2021-6449-.jpg',
      texto: 'Desayuno buffet. Visita de la ciudad a pie finalizando en la <strong>Plaza de San Marcos</strong>, incluyendo un taller de cristal veneciano. Tiempo libre para almorzar. <em class="small">(Almuerzo: Paquete Plus P+.)</em> Posibilidad de un paseo opcional en góndola por los canales. <em class="small">(Paseo en góndola: Paquete Plus P+.)</em> Alojamiento.',
    },
    { titulo: 'Venecia → Padua → Florencia', km: '280 km', texto: 'Desayuno buffet. Salida a Padua, con tiempo libre para visitar la Basílica de San Antonio. Continuación a <strong>Florencia</strong>, la ciudad más bella de Europa por su riqueza arquitectónica y artística. Alojamiento.' },
    {
      titulo: 'Florencia — Duomo y Ponte Vecchio',
      img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/View_of_Santa_Maria_del_Fiore_in_Florence.jpg/1280px-View_of_Santa_Maria_del_Fiore_in_Florence.jpg',
      texto: 'Desayuno. Recorreremos el centro artístico de la ciudad: el <strong>Duomo</strong>, el Campanile de Giotto, el Baptisterio de San Giovanni, la iglesia de San Lorenzo, la Plaza de la Signoria, la Loggia dei Lanzi, terminando en el Ponte Vecchio. <em class="small">(Almuerzo: Paquete Plus P+.)</em> Por la tarde, sugerimos visitar opcionalmente el museo de la Academia para admirar el David de Miguel Ángel. Alojamiento.',
    },
    { titulo: 'Florencia → Siena → Asís → Roma', km: '382 km', texto: 'Desayuno buffet y salida para uno de los días más completos del viaje. Poco después estaremos en la <strong>Plaza del Campo</strong> de Siena, escenario de la famosa "carrera del palio". Continuación a <strong>Asís</strong>, la ciudad de San Francisco, con tiempo libre para conocer sus basílicas superior e inferior. <em class="small">(Almuerzo en Asís: Paquete Plus P+.)</em> Continuación a Roma. Alojamiento.' },
    {
      titulo: 'Roma — Vaticano y ciudad eterna',
      img: 'https://images.unsplash.com/photo-1531572753322-ad063cecc140?q=80&w=800',
      texto: 'Desayuno buffet. Visita opcional detallada del <strong>Vaticano</strong>, sus museos y la capilla Sixtina. <em class="small">(Visita: Paquete Plus P+.)</em> Recorrido panorámico de la ciudad eterna. <em class="small">(Almuerzo: Paquete Plus P+.)</em> Por la tarde, posibilidad opcional de conocer la Roma barroca. Alojamiento.',
    },
    { titulo: 'Roma — Día libre (Nápoles y Capri opcional)', texto: 'Desayuno. Día libre en Roma. Sugerimos una excursión de todo el día para visitar Nápoles y la bella isla de <strong>Capri</strong>. Alojamiento.' },
    { titulo: 'Roma → Pisa → Costa Azul', km: '653 km', texto: 'Desayuno buffet y salida hacia <strong>Pisa</strong>. Tiempo libre para visitar el conjunto histórico con su famosa Torre Inclinada. <em class="small">(Almuerzo: Paquete Plus P+.)</em> Continuación hacia el norte siguiendo la Riviera de las Flores hasta Costa Azul. Alojamiento. <em class="small">Para los pasajeros que terminan su tour en Roma (variante de 18 días): desayuno y tiempo libre hasta el traslado al aeropuerto.</em>' },
    { titulo: 'Costa Azul → Barcelona', km: '682 km', texto: 'Desayuno. Por la mañana, salida a Arles, Nimes y Montpellier. Llegada a <strong>Barcelona</strong> a media tarde. Alojamiento.' },
    { titulo: 'Barcelona — Visita de ciudad', texto: 'Desayuno buffet. Visita panorámica de la ciudad, pasando por sus lugares más interesantes. <em class="small">(Almuerzo: Paquete Plus P+.)</em> Tarde libre. Alojamiento.' },
    { titulo: 'Barcelona → Zaragoza → Madrid', km: '635 km', texto: 'Desayuno y salida hacia Zaragoza, con una breve parada junto a la <strong>Basílica del Pilar</strong>. Continuación a Madrid. Alojamiento. <em class="small">Para los pasajeros que terminan servicios en Barcelona (variante de 21 días): desayuno buffet y, a la hora prevista, traslado al aeropuerto para tomar su vuelo de salida.</em>' },
    { titulo: 'Madrid — Vuelo de regreso', texto: 'Desayuno. Traslado al aeropuerto para tomar el vuelo de regreso.' },
  ],
  incluye: [
    'Traslados aeropuerto – hotel – aeropuerto, a la llegada y salida',
    'Alojamiento y desayuno buffet en hoteles de la categoría elegida',
    'Transporte en autobús de turismo',
    'Acompañamiento de un guía durante todo el recorrido europeo en bus desde Madrid',
    'Visitas indicadas en el itinerario con guías de habla hispana',
    'Paseo en barco por el río Rin',
    'Seguro de protección y asistencia en viaje MAPAPLUS',
    'Visitas con servicio de audio individual',
  ],
  noIncluye: [
    'Vuelos internacionales',
    'Impuesto de ciudad: <strong>$113 USD</strong> (18 días) / <strong>$122 USD</strong> (21 o 22 días), al reservar',
    'Comidas no indicadas',
    'Gastos personales',
  ],
  plus: {
    precio: '835 (18 días, Madrid / Roma) / 870 (21 o 22 días, Madrid / Barcelona o Madrid)',
    comidas: ['Cena de tapas en Madrid', 'Almuerzo en Toledo', 'Almuerzo snack en crucero por el Rin', 'Almuerzo en Sirmione', 'Almuerzo en Venecia', 'Almuerzo en Florencia', 'Almuerzo en Asís', 'Almuerzo en Roma', 'Almuerzo en Pisa', 'Almuerzo en Barcelona'],
    extras: ['Visita nocturna en Madrid', 'Visita a Toledo', 'Paseo en Bateaux Mouche', 'Subida a la torre Eiffel (2º piso)', 'Paseo en góndola en Venecia', 'El Vaticano: museos y capilla Sixtina'],
  },
  precios: {
    columnas: ['May – Jun', 'Jul – Ago', 'Sep – Oct', 'Nov – Feb 27*', 'Dic (fechas especiales)', 'Mar – Abr 27'],
    mejorCol: 3,
    filas: [
      { tour: '18 días<br><small class="text-muted fw-normal">Madrid / Roma<br>Iti OC270</small>', categoria: 'Confort 3*/4*', valores: ['3,400', '3,225', '3,400', '2,960', '3,225', '3,310'] },
      { tour: '', categoria: 'Superior 4*', valores: ['3,725', '3,480', '3,725', '3,225', '3,480', '3,650'] },
      { tour: '21 días<br><small class="text-muted fw-normal">Madrid / Barcelona<br>Iti OC271</small>', categoria: 'Confort 3*/4*', valores: ['3,865', '3,665', '3,865', '3,395', '3,665', '3,755'] },
      { tour: '', categoria: 'Superior 4*', valores: ['4,190', '3,920', '4,190', '3,665', '3,920', '4,095'] },
      { tour: '22 días<br><small class="text-muted fw-normal">Madrid / Madrid<br>Iti OC272</small>', categoria: 'Confort 3*/4*', valores: ['3,955', '3,740', '3,955', '3,470', '3,740', '3,850'] },
      { tour: '', categoria: 'Superior 4*', valores: ['4,315', '4,005', '4,315', '3,770', '4,005', '4,230'] },
    ],
    nota: '*Nov–Feb 27, excepto fechas especiales de diciembre (varían según variante: 18 días 11-18-25 dic · 21 y 22 días 4-11-18-25 dic). Suplemento individual (resto de temporada / nov–feb 27): 18 días Confort $1,355/$1,065 · Superior $1,770/$1,385 · 21 días Confort $1,575/$1,260 · Superior $1,990/$1,580 · 22 días Confort $1,665/$1,340 · Superior $2,115/$1,700. Impuesto de ciudad se paga al reservar.',
  },
  hoteles: [
    { ciudad: 'Madrid', confort: 'Praga / Muralto / NH Ribera del Manzanares / Hotel E-Kilibrio', superior: 'Rafael Atocha / Agumar / Meliá Castilla / 1881 Ventas' },
    { ciudad: 'Burdeos', ambos: 'Novotel Lac / Novotel Bordeaux Mérignac' },
    { ciudad: 'París', confort: 'B&B Porte d\'Orléans / Ibis Porte d\'Orléans / Ibis La Défense', superior: 'Mercure Porte d\'Orléans / Novotel La Défense' },
    { ciudad: 'Frankfurt', confort: 'Novotel Frankfurt City / Mercure Hotel & Residenz Frankfurt Messe', superior: 'Maritim / Mövenpick Hotel Frankfurt City' },
    { ciudad: 'Basilea', ambos: 'Essential Dorint / Courtyard Basel' },
    { ciudad: 'Milán', ambos: 'Starhotel Business Palace' },
    { ciudad: 'Venecia', confort: 'Smart Hotel Holiday', superior: 'Delfino' },
    { ciudad: 'Florencia', confort: 'Mirage / The Gate', superior: 'Raffaello / NH' },
    { ciudad: 'Roma', confort: 'Occidental Aran Park / Cristoforo Colombo', superior: 'Precise Aran Mantegna / Midas' },
    { ciudad: 'Costa Azul', ambos: 'Novotel Sophia Antipolis / Mercure Sophia Antipolis / Ibis Cannes Mandelieu' },
    { ciudad: 'Barcelona', confort: 'Exe Barbera Parc / Exe Campus / Hotel Acta Sant Just / Ibis Styles Sant Joan Despí', superior: 'Porta Fira / Hampton by Hilton Fira / Alexandre Fira Congress / Hesperia Sant Just' },
  ],
  fechas: {
    libre: '<strong>A Madrid (viernes):</strong> may 01, 08, 15, 22, 29 · jun 05, 12, 19, 26 · jul 03, 10, 17, 24, 31 · ago 07, 14, 21, 28 · sep 04, 11, 18, 25 · oct 02, 09, 16, 23, 30 · nov 06, 13, 20, 27 · dic 04, 11, 18, 25. <span class="text-muted">Fechas de salida 2026; también hay salidas 2027 (ene–abr).</span>',
  },
  relacionados: [
    { slug: 'la-pequena-gira-europea', title: 'La Pequeña Gira Europea', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Kapellbruecke.JPG/1280px-Kapellbruecke.JPG' },
    { slug: 'europa-en-bandeja-desde-madrid', title: 'Europa en Bandeja: Desde Madrid', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Grand-Place%2C_Brussels_-_panorama%2C_June_2018.jpg/1280px-Grand-Place%2C_Brussels_-_panorama%2C_June_2018.jpg' },
    { slug: 'la-europa-de-siempre-desde-madrid', title: 'La Europa de Siempre: Desde Madrid', img: '/Assets/img/espana/madrid-hero.jpg' },
  ],
  cta: '¿List@ para tu Querida Europa?',
};
