// =============================================================================
// DATOS CURADOS DE LOS PAQUETES (analizados a partir de los flyers de Supabase)
// =============================================================================
// Cada entrada esta indexada por el NOMBRE DE ARCHIVO del flyer (la ultima parte
// de image_url). El generador (gen-paquetes.cjs) cruza esto con los datos en vivo
// de la tabla `promotions` para resolver la URL real de la imagen y la categoria.
//
// Reglas de contenido (pedido de la duena):
//   - SIN fechas de salida ni precios: eso lo confirma la vendedora.
//   - `duration` es opcional y describe el largo del paquete (no es una fecha).
//   - `countries`: slugs que coinciden con las paginas de pais existentes
//     (peru, mexico, espana, estados-unidos, argentina, emiratos-arabes, china,
//      japon, tailandia, italia). Puede ir vacio si el destino no tiene pagina.
//
// Para corregir/ampliar: edita aqui y vuelve a correr  node tools/gen-paquetes.cjs
// =============================================================================

module.exports = [
  // ---- USA / Estados Unidos ----
  {
    file: 'angeles-vegas-canon-usa.jpg',
    slug: 'usa-los-angeles-las-vegas-gran-canon',
    title: 'Los Ángeles, Las Vegas y el Gran Cañón',
    subtitle: 'Lo mejor del oeste americano en un solo viaje.',
    duration: '6 días / 5 noches',
    countries: ['estados-unidos'],
    highlights: ['Los Ángeles y Hollywood', 'Las Vegas y su vida nocturna', 'El imponente Gran Cañón', 'Circuito guiado en español'],
  },
  {
    file: 'mundial-2026.jpg',
    slug: 'mundial-2026-usa',
    title: 'Vive el Mundial 2026 en USA',
    subtitle: 'San Francisco y Nueva York al ritmo del Mundial.',
    countries: ['estados-unidos'],
    highlights: ['San Francisco y el Golden Gate', 'Nueva York y sus íconos', 'Ambiente mundialista', 'Vuelos y hoteles incluidos'],
  },
  {
    file: 'na-circuitos-turisticos-usa.jpg',
    slug: 'circuitos-usa',
    title: 'Circuitos Turísticos por USA',
    subtitle: 'Varias rutas para descubrir lo mejor de Estados Unidos.',
    countries: ['estados-unidos'],
    highlights: ['Circuito Costa Este', 'Washington y Nueva York', 'Las Vegas y el oeste', 'Opciones para todos los gustos'],
  },
  {
    file: 'na-orlando.jpg',
    slug: 'orlando-fly-and-drive',
    title: 'Orlando — Fly & Drive',
    subtitle: 'La capital mundial de los parques temáticos.',
    countries: ['estados-unidos'],
    highlights: ['Parques temáticos de Orlando', 'Hotel Meliá Orlando', 'Auto a tu disposición', 'Salida confirmada'],
  },
  {
    file: 'new-york-washingtong-usa.jpg',
    slug: 'nueva-york-y-washington',
    title: 'Nueva York y Washington',
    subtitle: 'Dos ciudades emblemáticas de la costa este.',
    duration: '6 días / 5 noches',
    countries: ['estados-unidos'],
    highlights: ['Nueva York: Times Square y Central Park', 'Washington D.C. y sus monumentos', 'Circuito guiado en español'],
  },
  {
    file: 'vegas-canon-usa.jpg',
    slug: 'las-vegas-y-gran-canon',
    title: 'Las Vegas y el Gran Cañón',
    subtitle: 'Escapada exprés al desierto y sus luces.',
    duration: '4 días / 3 noches',
    countries: ['estados-unidos'],
    highlights: ['Las Vegas y sus casinos', 'Excursión al Gran Cañón', 'Escapada corta e intensa'],
  },
  {
    file: 'washingtong-ny-boston-usa.jpg',
    slug: 'washington-nueva-york-y-boston',
    title: 'Washington, Nueva York y Boston',
    subtitle: 'Gran recorrido por la costa este de USA.',
    duration: '10 días / 9 noches',
    countries: ['estados-unidos'],
    highlights: ['Washington D.C.', 'Nueva York', 'Boston histórica', 'Circuito completo guiado'],
  },

  // ---- Asia: China / Japón / Corea / Dubái / Turquía / India ----
  {
    file: 'china-milenaria.jpg',
    slug: 'china-milenaria',
    title: 'China Milenaria',
    subtitle: 'Templos, murallas y ciudades imperiales.',
    duration: '13 días / 10 noches',
    countries: ['china'],
    highlights: ['La Gran Muralla China', 'Pekín y la Ciudad Prohibida', 'Xi’an y los guerreros de terracota', 'Shanghái moderna'],
  },
  {
    file: 'china-tokio.jpg',
    slug: 'china-clasica-y-tokio',
    title: 'China Clásica y Tokio',
    subtitle: 'Lo mejor de China sumado a la vibrante Tokio.',
    duration: '14 días / 13 noches',
    countries: ['china', 'japon'],
    highlights: ['Pekín y la Gran Muralla', 'Shanghái', 'Tokio futurista', 'Dos culturas en un viaje'],
  },
  {
    file: 'corea-japon.jpg',
    slug: 'corea-y-japon-tradicional',
    title: 'Corea y Japón Tradicional',
    subtitle: 'Tradición y modernidad del Lejano Oriente.',
    duration: '14 días / 12 noches',
    countries: ['japon'],
    highlights: ['Seúl y su cultura', 'Tokio y Kioto', 'Templos y tradición', 'Gastronomía oriental'],
  },
  {
    file: 'coreo-pekin-shangai.jpg',
    slug: 'corea-pekin-y-shanghai',
    title: 'Corea con Pekín y Shanghái',
    subtitle: 'Gran circuito por Corea y China.',
    duration: '15 días / 12 noches',
    countries: ['china'],
    highlights: ['Seúl', 'Pekín y la Gran Muralla', 'Shanghái', 'Circuito guiado en español'],
  },
  {
    file: 'dubai.jpg',
    slug: 'lo-mejor-de-dubai',
    title: 'Lo Mejor de Dubái',
    subtitle: 'Lujo y modernidad en el desierto, oferta 2x1.',
    countries: ['emiratos-arabes'],
    highlights: ['Burj Khalifa', 'Dubái Marina', 'Safari en el desierto', 'Opción 4 Emiratos'],
  },
  {
    file: 'turquia-y-dubai.jpg',
    slug: 'mega-turquia-y-dubai',
    title: 'Mega Turquía y Dubái',
    subtitle: 'Estambul, Capadocia y el brillo de Dubái.',
    duration: '11 días / 10 noches',
    countries: ['emiratos-arabes'],
    highlights: ['Estambul y la Mezquita Azul', 'Capadocia y sus globos', 'Dubái y el Burj Khalifa', 'Dos destinos en un viaje'],
  },
  {
    file: 'india-triangulo-dorado-7d.jpg',
    slug: 'india-triangulo-dorado',
    title: 'India — Triángulo Dorado',
    subtitle: 'Delhi, Agra y Jaipur, la ruta clásica de la India.',
    duration: '7 días / 6 noches',
    countries: [],
    highlights: ['Delhi', 'El Taj Mahal en Agra', 'Jaipur, la ciudad rosa', 'Cultura y color'],
  },
  {
    file: 'india-triangulo-dorado-con-varanasi.jpg',
    slug: 'india-triangulo-dorado-con-varanasi',
    title: 'India — Triángulo Dorado con Varanasi',
    subtitle: 'La ruta clásica más la espiritualidad de Varanasi.',
    duration: '9 días / 8 noches',
    countries: [],
    highlights: ['Delhi, Agra y Jaipur', 'El Taj Mahal', 'Varanasi y el río Ganges', 'Ceremonias sagradas'],
  },
  {
    file: 'india-yoga-meditacion-10d9n.jpg',
    slug: 'india-yoga-y-meditacion',
    title: 'India con Yoga y Meditación',
    subtitle: 'Un viaje para el cuerpo y el espíritu.',
    duration: '10 días / 9 noches',
    countries: [],
    highlights: ['Yoga y meditación', 'Templos y ashrams', 'Triángulo Dorado', 'Experiencia transformadora'],
  },
  {
    file: 'mejor-india-nepal-12d.jpg',
    slug: 'mejor-india-y-nepal',
    title: 'Lo Mejor de India y Nepal',
    subtitle: 'Del Taj Mahal a los Himalayas.',
    duration: '12 días / 11 noches',
    countries: [],
    highlights: ['Triángulo Dorado de India', 'Katmandú', 'Paisajes del Himalaya', 'Cultura y espiritualidad'],
  },

  // ---- Europa ----
  {
    file: 'conoce-europa.jpg',
    slug: 'conoce-europa-a-tu-estilo',
    title: 'Conoce Europa a tu Estilo',
    subtitle: 'Gran Tour Europa en sus versiones clásica y lujo.',
    countries: ['espana', 'italia'],
    highlights: ['Madrid y Barcelona', 'París', 'Roma y Venecia', 'Versión Clásica o Lujo'],
  },
  {
    file: 'gran-tour-europa.jpg',
    slug: 'gran-tour-de-europa',
    title: 'Gran Tour de Europa',
    subtitle: 'Las capitales imprescindibles del viejo continente.',
    countries: ['espana', 'italia'],
    highlights: ['Madrid', 'París', 'Roma', 'Venecia y más'],
  },
  {
    file: 'tour-europa.jpg',
    slug: 'gran-tour-europa-desde-lisboa',
    title: 'Gran Tour Europa desde Lisboa',
    subtitle: 'Recorre Europa empezando por Portugal.',
    countries: ['espana', 'italia'],
    highlights: ['Lisboa', 'Madrid', 'París', 'Roma'],
  },
  {
    file: 'mega-europa-especial-ii.jpg',
    slug: 'mega-europa-especial',
    title: 'Mega Europa Especial II',
    subtitle: 'El recorrido más completo por Europa.',
    countries: ['espana', 'italia'],
    highlights: ['Multidestino europeo', 'Ciudades imperiales', 'Italia y España', 'Circuito guiado'],
  },
  {
    file: 'eu-londres-madrid.jpg',
    slug: 'bellezas-de-londres-a-madrid',
    title: 'Bellezas de Londres a Madrid',
    subtitle: 'Del Támesis al corazón de España.',
    duration: '17 días / 16 noches',
    countries: ['espana'],
    highlights: ['Londres', 'París', 'Madrid', 'Gran circuito europeo'],
  },
  {
    file: 'grecia.jpg',
    slug: 'grecia-clasica-e-islas-cicladas',
    title: 'Grecia Clásica e Islas Cícladas',
    subtitle: 'Atenas y el azul del mar Egeo.',
    duration: '11 días / 10 noches',
    countries: [],
    highlights: ['Atenas y la Acrópolis', 'Islas Cícladas', 'Santorini y Mykonos', 'Historia y playas'],
  },
  {
    file: 'grecia-2.jpg',
    slug: 'tesoros-de-grecia',
    title: 'Tesoros de Grecia',
    subtitle: 'Lo esencial de la cuna de Occidente.',
    duration: '8 días / 7 noches',
    countries: [],
    highlights: ['Atenas', 'Sitios arqueológicos', 'Mitología griega', 'Gastronomía mediterránea'],
  },
  {
    file: 'grecia-3.jpg',
    slug: 'encantos-de-atenas-e-islas',
    title: 'Encantos de Atenas e Islas',
    subtitle: 'Atenas con escapada a las islas griegas.',
    duration: '8 días / 7 noches',
    countries: [],
    highlights: ['Atenas y la Acrópolis', 'Islas griegas', 'Pueblos blancos', 'Atardeceres del Egeo'],
  },

  // ---- Sudamérica ----
  {
    file: 'carnavales-peruanos.jpg',
    slug: 'carnavales-peruanos',
    title: 'Carnavales Peruanos',
    subtitle: 'Vive la fiesta y la tradición del Perú.',
    countries: ['peru'],
    highlights: ['Carnavales regionales', 'Música y danza', 'Gastronomía peruana', 'Cultura viva'],
  },
  {
    file: 'iguazu.jpg',
    slug: 'escapada-iguazu',
    title: 'Escapada a Iguazú',
    subtitle: 'Las cataratas más impresionantes de Sudamérica.',
    countries: ['argentina'],
    highlights: ['Cataratas del Iguazú', 'Selva subtropical', 'Garganta del Diablo', 'Naturaleza pura'],
  },
  {
    file: 'atacama-chile.jpg',
    slug: 'san-pedro-de-atacama',
    title: 'San Pedro de Atacama',
    subtitle: 'El desierto más árido del mundo.',
    countries: [],
    highlights: ['Valle de la Luna', 'Géiseres del Tatio', 'Lagunas altiplánicas', 'Cielos estrellados'],
  },
  {
    file: 'patagonia-chile.jpg',
    slug: 'patagonia-chile',
    title: 'Patagonia Chilena',
    subtitle: 'Glaciares, montañas y naturaleza salvaje.',
    countries: [],
    highlights: ['Torres del Paine', 'Glaciares', 'Paisajes patagónicos', 'Aventura al sur del mundo'],
  },
  {
    file: 'puerto-varas-chile.jpg',
    slug: 'puerto-varas-chile',
    title: 'Puerto Varas',
    subtitle: 'Lagos, volcanes y encanto del sur de Chile.',
    countries: [],
    highlights: ['Lago Llanquihue', 'Volcán Osorno', 'Saltos del Petrohué', 'Pueblos del sur'],
  },
  {
    file: 'cartagena.jpg',
    slug: 'cartagena-de-indias',
    title: 'San Valentín en Cartagena',
    subtitle: 'Romance y color en el Caribe colombiano.',
    countries: [],
    highlights: ['Ciudad amurallada', 'Playas del Caribe', 'Atardeceres', 'Ambiente romántico'],
  },
  {
    file: 'colombia.jpg',
    slug: 'colombia-medellin-bogota-cartagena',
    title: 'Con Sabor a Colombia',
    subtitle: 'Medellín, Bogotá y Cartagena en un viaje.',
    countries: [],
    highlights: ['Medellín, ciudad de la eterna primavera', 'Bogotá', 'Cartagena amurallada', 'Cultura y playa'],
  },
  {
    file: 'medellin.jpg',
    slug: 'medellin-y-las-tres-perlas-del-caribe',
    title: 'Medellín y las Tres Perlas del Caribe',
    subtitle: 'Lo mejor de Colombia y el Caribe.',
    duration: '7 días / 6 noches',
    countries: [],
    highlights: ['Medellín', 'Cartagena', 'San Andrés', 'Sol y playa'],
  },
  {
    file: 'escapada-medellin.jpg',
    slug: 'escapada-a-medellin',
    title: 'Escapada a Medellín',
    subtitle: 'La ciudad de la eterna primavera.',
    duration: '6 días / 5 noches',
    countries: [],
    highlights: ['Comuna 13', 'Pueblo de Guatapé', 'Vida nocturna', 'Clima primaveral'],
  },
  {
    file: 'rio-de-janeiro.jpg',
    slug: 'rio-de-janeiro',
    title: 'Río de Janeiro',
    subtitle: 'La ciudad maravillosa de Brasil.',
    countries: [],
    highlights: ['Cristo Redentor', 'Pan de Azúcar', 'Playas de Copacabana e Ipanema', 'Ambiente carioca'],
  },
  {
    file: 'rio-y-buzios.jpg',
    slug: 'rio-de-janeiro-y-buzios',
    title: 'Río de Janeiro y Búzios',
    subtitle: 'La gran ciudad más el paraíso de Búzios.',
    countries: [],
    highlights: ['Río de Janeiro', 'Playas de Búzios', 'Sol y mar', 'Relax y diversión'],
  },

  // ---- Caribe y Centroamérica ----
  {
    file: 'ca-curacao.jpg',
    slug: 'curacao-todo-incluido',
    title: 'Curaçao Todo Incluido',
    subtitle: 'Playa, color y mar turquesa en grupo.',
    countries: [],
    highlights: ['Playas de aguas turquesas', 'Todo incluido', 'Willemstad colorida', 'Salida en grupo confirmada'],
  },
  {
    file: 'ca-isla-feliz.jpg',
    slug: 'aruba-isla-feliz',
    title: 'Aruba — La Isla Feliz',
    subtitle: 'Semana Santa en el Caribe holandés.',
    countries: [],
    highlights: ['Eagle Beach', 'Aguas cristalinas', 'Clima perfecto', 'Ambiente relajado'],
  },
  {
    file: 'ca-montego-bay.jpg',
    slug: 'montego-bay-jamaica',
    title: 'Montego Bay, Jamaica',
    subtitle: 'La magia del Caribe jamaiquino.',
    countries: [],
    highlights: ['Playas de Montego Bay', 'Resorts todo incluido', 'Ritmo reggae', 'Aguas turquesas'],
  },
  {
    file: 'ca-punta-cana.jpg',
    slug: 'punta-cana-semana-santa',
    title: 'Punta Cana — Semana Santa',
    subtitle: 'El Caribe dominicano en su mejor época.',
    countries: [],
    highlights: ['Playas de arena blanca', 'Resorts todo incluido', 'Palmeras y mar', 'Diversión sin límites'],
  },
  {
    file: 'punta-cana.jpg',
    slug: 'punta-cana',
    title: 'Punta Cana',
    subtitle: 'El paraíso caribeño todo incluido.',
    countries: [],
    highlights: ['Playas de ensueño', 'Todo incluido', 'Excursión a Isla Saona', 'Sol todo el año'],
  },
  {
    file: 'punta-cana-2.jpg',
    slug: 'punta-cana-trs-turquesa',
    title: 'Punta Cana — TRS Turquesa (Solo Adultos)',
    subtitle: 'Lujo solo para adultos con Palladium.',
    countries: [],
    highlights: ['Resort solo adultos', 'TRS Turquesa Hotel', 'Todo incluido premium', 'Playa privada'],
  },
  {
    file: 'punta-cana-3.jpg',
    slug: 'punta-cana-grand-palladium',
    title: 'Punta Cana — Grand Palladium',
    subtitle: 'Ideal para familias con Palladium.',
    countries: [],
    highlights: ['Grand Palladium Resort & Spa', 'Todo incluido', 'Ideal para familias', 'Playa y piscinas'],
  },
  {
    file: 'ca-varadero.jpg',
    slug: 'varadero-royalton',
    title: 'Varadero — Royalton Hicacos',
    subtitle: 'Las mejores playas de Cuba, todo incluido.',
    countries: [],
    highlights: ['Royalton Hicacos', 'Playas de Varadero', 'Solo adultos', 'Todo incluido'],
  },
  {
    file: 'vive-varadero.jpg',
    slug: 'vive-varadero',
    title: 'Vive Varadero',
    subtitle: 'El Caribe cubano te espera.',
    countries: [],
    highlights: ['Playas de Varadero', 'Resorts todo incluido', 'Aguas turquesas', 'Sol y descanso'],
  },
  {
    file: 'donde-el-sol.jpg',
    slug: 'especial-caribe-sol-y-amor',
    title: 'Especial Caribe — Donde el Sol y el Amor se Encuentran',
    subtitle: 'Escapadas al Caribe y Colombia.',
    countries: [],
    highlights: ['Varadero y La Habana', 'Medellín', 'Sol y playa', 'Varias salidas'],
  },

  // ---- México (Palladium) ----
  {
    file: 'costa-mujeres.jpg',
    slug: 'costa-mujeres-trs-coral',
    title: 'Costa Mujeres — TRS Coral (Solo Adultos)',
    subtitle: 'Lujo solo para adultos en la Riviera mexicana.',
    countries: ['mexico'],
    highlights: ['TRS Coral Hotel', 'Solo adultos', 'Todo incluido premium', 'Cancún cercano'],
  },
  {
    file: 'costa-mujeres-2.jpg',
    slug: 'costa-mujeres-grand-palladium',
    title: 'Costa Mujeres — Grand Palladium',
    subtitle: 'Caribe mexicano ideal para familias.',
    countries: ['mexico'],
    highlights: ['Grand Palladium Select', 'Todo incluido', 'Ideal para familias', 'Playas de Cancún'],
  },
  {
    file: 'rivera-maya.jpg',
    slug: 'riviera-maya-trs-yucatan',
    title: 'Riviera Maya — TRS Yucatán (Solo Adultos)',
    subtitle: 'Exclusividad solo para adultos en el Caribe.',
    countries: ['mexico'],
    highlights: ['TRS Yucatán Hotel', 'Solo adultos', 'Todo incluido premium', 'Cenotes y playas'],
  },
  {
    file: 'rivera-maya-2.jpg',
    slug: 'riviera-maya-grand-palladium',
    title: 'Riviera Maya — Grand Palladium',
    subtitle: 'El Caribe mexicano para toda la familia.',
    countries: ['mexico'],
    highlights: ['Grand Palladium Kantenah', 'Todo incluido', 'Ideal para familias', 'Riviera Maya'],
  },
  {
    file: 'jamaica-2.jpg',
    slug: 'jamaica-grand-palladium',
    title: 'Jamaica — Grand Palladium',
    subtitle: 'Todo incluido en el corazón del Caribe.',
    countries: [],
    highlights: ['Grand Palladium Lady Hamilton', 'Resort & Spa', 'Todo incluido', 'Playas jamaiquinas'],
  },

  // ---- Multi-promo (collage) ----
  {
    file: 'febrero-promos.jpg',
    slug: 'febrero-en-pareja',
    title: 'Febrero en Pareja',
    subtitle: 'Escapadas internacionales para dos.',
    countries: [],
    highlights: ['China', 'Turquía y Dubái', 'Tailandia', 'Balcanes'],
  },
];
